import {
  LayoutDashboard,
  ArrowLeftRight,
  Repeat,
  CalendarClock,
  Tags,
  PieChart,
  Target,
  Wallet,
  FileBarChart,
  Link2,
  User,
  Building2,
  Percent,
  Users,
  Truck,
  Upload,
  GitCompare,
  List,
  Lock,
  Settings,
  Shield,
  Menu,
  LogOut,
  Eye,
  TrendingUp,
  TrendingDown,
  CircleDollarSign,
  Hourglass,
  AlertTriangle,
  Mail,
  Smartphone,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  Minus,
  Sparkles,
  Landmark,
  FileSpreadsheet,
  PenLine,
  Trash2,
  Pause,
  Play,
  CircleCheck,
  MessageCircle,
  BarChart3,
  Layers,
  Scale,
  ClipboardList,
  Receipt,
  Banknote,
  PiggyBank,
  CreditCard,
  LineChart,
  Loader2,
  Inbox,
  CalendarDays,
  Star,
  Circle,
  Plus,
  X,
  FolderTree,
  Briefcase,
  Clock,
  FileText,
  Table,
  AlertCircle,
  ArrowRight,
  Bell,
  Heart,
  Smile,
  Info,
  Ticket,
  RefreshCw,
  GraduationCap,
  ExternalLink,
  Video,
  MessageSquare,
  CheckCircle,
  XCircle,
  ChevronLeft,
  Rocket,
  BookOpen,
} from "lucide-react";

/** Icones de navegacao (Lucide) — chave = id da rota em constants.js */
export const NAV_ICON_MAP = {
  dashboard: LayoutDashboard,
  lancamentos: Receipt,
  recorrencias: Repeat,
  "contas-pagar": CalendarClock,
  "resumo-anual": LineChart,
  categorias: Tags,
  orcamento: PieChart,
  "orcado-realizado": GitCompare,
  metas: Target,
  "resultado-centro-custo": Layers,
  projetos: Briefcase,
  "resultado-cliente": Users,
  "resultado-projeto": Briefcase,
  contas: Wallet,
  relatorios: ClipboardList,
  whatsapp: MessageCircle,
  "integracao-pf-pj": Users,
  "open-finance": Link2,
  perfil: User,
  seguranca: Shield,
  "plano-assinatura": CircleDollarSign,
  dre: BarChart3,
  plano: FolderTree,
  impostos: Percent,
  clientes: Users,
  fornecedores: Truck,
  importacoes: Upload,
  conciliacao: GitCompare,
  balancete: Scale,
  fechamento: Lock,
  empresa: Building2,
  tutoriais: GraduationCap,
  ajuda: MessageCircle,
  suporte: Ticket,
  notificacoes: Bell,
};

export const ADMIN_ICON_MAP = {
  operacoes: LayoutDashboard,
  homologacao: CheckCircle,
  homologacaoReal: ClipboardList,
  saas: CircleDollarSign,
  tenants: Users,
  beta: Sparkles,
  pagamentos: CreditCard,
  release: Rocket,
  guia: BookOpen,
};

export function AdminNavIcon({ name, size = 18, strokeWidth = 1.75, className = "" }) {
  const Icon = ADMIN_ICON_MAP[name] || Shield;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}

export function NavIcon({ name, size = 16, strokeWidth = 2, className = "" }) {
  const Icon = NAV_ICON_MAP[name];
  if (!Icon) return <Minus size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}

export function TrendIcon({ dir, size = 14 }) {
  if (dir === "up") return <ArrowUpRight size={size} strokeWidth={2.25} aria-hidden />;
  if (dir === "down") return <ArrowDownRight size={size} strokeWidth={2.25} aria-hidden />;
  return <Minus size={size} strokeWidth={2.25} aria-hidden />;
}

export {
  LayoutDashboard,
  ArrowLeftRight,
  Repeat,
  CalendarClock,
  Tags,
  PieChart,
  Target,
  Wallet,
  FileBarChart,
  Link2,
  User,
  Building2,
  Users,
  Shield,
  Menu,
  LogOut,
  Eye,
  TrendingUp,
  TrendingDown,
  CircleDollarSign,
  Hourglass,
  AlertTriangle,
  Mail,
  Smartphone,
  Sparkles,
  Landmark,
  FileSpreadsheet,
  PenLine,
  Trash2,
  Pause,
  Play,
  CircleCheck,
  MessageCircle,
  ArrowUpRight,
  ArrowDownRight,
  ArrowDownLeft,
  Banknote,
  PiggyBank,
  CreditCard,
  LineChart,
  Loader2,
  Inbox,
  CalendarDays,
  Star,
  Circle,
  Plus,
  X,
  ClipboardList,
  Receipt,
  Clock,
  Lock,
  FolderTree,
  Briefcase,
  FileText,
  Table,
  AlertCircle,
  ArrowRight,
  Bell,
  Heart,
  Smile,
  Info,
  BarChart3,
  Layers,
  Ticket,
  RefreshCw,
  GraduationCap,
  ExternalLink,
  Video,
  MessageSquare,
  Upload,
  GitCompare,
  CheckCircle,
  XCircle,
  ChevronLeft,
};
