/** Espelha server/auth/permissions.js MENU_PERMISSION_MAP */
export const MENU_PERMISSION_MAP = {
  dashboard: "state.read",
  lancamentos: "state.read",
  recorrencias: "recorrencias.view",
  "contas-pagar": "state.read",
  "resumo-anual": "relatorios.view",
  dre: "relatorios.view",
  contas: "contas.manage",
  plano: "contas.manage",
  impostos: "relatorios.view",
  clientes: "clientes.manage",
  projetos: "projetos.view",
  "resultado-cliente": "relatorios.view",
  "resultado-projeto": "relatorios.view",
  fornecedores: "state.read",
  importacoes: "importacoes.view",
  conciliacao: "relatorios.view",
  balancete: "relatorios.view",
  fechamento: "relatorios.view",
  "resultado-centro-custo": "centro_custo.view",
  "orcado-realizado": "relatorios.view",
  relatorios: "relatorios.view",
  whatsapp: "whatsapp.view",
  "integracao-pf-pj": "integracao.view",
  "open-finance": "openfinance.view",
  tutoriais: "state.read",
  suporte: "state.read",
  empresa: "config.empresa",
  equipe: "equipe.view",
  seguranca: "config.seguranca",
  "plano-assinatura": "billing.view",
};
